$(window).load(function(){
	$('.loader').delay(1000).fadeOut(1000)
	$('#1').click(function(){
		$('g-cube').ghighlight('all')
	})
	$('#2').click(function(){
		$('g-cube').ghighlight('flcross')
	})
	$('#3').click(function(){
		$('g-cube').ghighlight('fl')
	})
	$('#4').click(function(){
		$('g-cube').ghighlight('f2l')
	})
	$('#5').click(function(){
		$('g-cube').ghighlight('eoll')
	})
	$('#6').click(function(){
		$('g-cube').ghighlight('oll')
	})
	$('#7').click(function(){
		$('g-cube').ghighlight('coll')
	})
	$('#8').click(function(){
		$('g-cube').ghighlight('all')
	})
})