$('iframe').load(function(){
	~navigator.userAgent.indexOf('Firefox')&&(cube.hideIntroverts(),$('.face').css('backface-visibility','visible'))
	$('.loader').delay(2000).fadeOut(1000)
	$('#1').click(function(){
		$('g-cube').ghighlight('all')
	})
	$('#2').click(function(){
		$('g-cube').ghighlight('flcross')
	})
	$('#3').click(function(){
		$('g-cube').ghighlight('fl')
	})
	$('#4').click(function(){
		$('g-cube').ghighlight('f2l')
	})
	$('#5').click(function(){
		$('g-cube').ghighlight('eoll')
	})
	$('#6').click(function(){
		$('g-cube').ghighlight('oll')
	})
	$('#7').click(function(){
		$('g-cube').ghighlight('coll')
	})
	$('#8').click(function(){
		$('g-cube').ghighlight('all')
	})
})